FROM python:3.11-slim

WORKDIR /workspace

COPY requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY . /workspace

CMD ["bash","-lc","streamlit run ui/App.py --server.address=0.0.0.0 --server.port=8501"]
