version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: headhunter_postgres
    environment:
      POSTGRES_DB: headhunter_db
      POSTGRES_USER: headhunter_user
      POSTGRES_PASSWORD: headhunter_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: